# Generated by Django 6.0 on 2025-12-29 11:24

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoProposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(help_text='Código curto do tipo de proposição (até 10 caracteres)', max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Proposição',
                'verbose_name_plural': 'Tipos de Proposição',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.comissao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ORDINARIA', 'Ordinária'), ('EXTRAORDINARIA', 'Extraordinária')], max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('pauta', models.TextField(blank=True)),
                ('ata', models.TextField(blank=True)),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reunioes', to='www.comissao')),
            ],
            options={
                'unique_together': {('comissao', 'numero', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('numero', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('numero_formatado', models.CharField(max_length=20)),
                ('ementa', models.TextField()),
                ('data_publicacao', models.DateField()),
                ('link_proposicao', models.CharField(blank=True, max_length=400, null=True)),
                ('autores', models.ManyToManyField(related_name='proposicoes_autoria', to='www.autor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposicoes', to='www.tipoproposicao')),
            ],
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.comissao')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='www.proposicao')),
            ],
            options={
                'ordering': ['data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RELATOR', 'Parecer do Relator'), ('VENCIDO', 'Parecer Vencido')], max_length=30)),
                ('parecer', models.CharField(max_length=200)),
                ('texto', django_ckeditor_5.fields.CKEditor5Field()),
                ('data_apresentacao', models.DateField()),
                ('relator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.autor')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.reuniao')),
                ('tramitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='www.tramitacao')),
            ],
            options={
                'ordering': ['data_apresentacao'],
            },
        ),
        migrations.AddConstraint(
            model_name='proposicao',
            constraint=models.UniqueConstraint(fields=('tipo', 'numero_formatado'), name='unique_numero_formatado_por_tipo'),
        ),
    ]
