# Generated by Django 6.0 on 2025-12-28 03:40

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoProposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(help_text='Código curto do tipo de proposição (até 10 caracteres)', max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Proposição',
                'verbose_name_plural': 'Tipos de Proposição',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.comissao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('ementa', models.TextField()),
                ('link_proposicao', models.CharField(blank=True, max_length=400, null=True)),
                ('autores', models.ManyToManyField(related_name='proposicoes_autoria', to='www.autor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposicoes', to='www.tipoproposicao')),
            ],
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_relatoria', models.DateField(blank=True, null=True)),
                ('reuniao', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, max_length=2000, null=True)),
                ('parecer', models.CharField(blank=True, max_length=100, null=True)),
                ('texto_parecer', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Texto do Parecer')),
                ('data_devolucao_relatoria', models.DateField(blank=True, null=True)),
                ('parecer_vencido', models.CharField(blank=True, max_length=100, null=True)),
                ('texto_parecer_vencido', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Texto do Parecer Vencido')),
                ('data_devolucao_relatoria_vencido', models.DateField(blank=True, null=True)),
                ('data_publicacao_parecer', models.DateField(blank=True, null=True)),
                ('data_saida_comissao', models.DateField(blank=True, null=True)),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.comissao')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='www.proposicao')),
                ('relator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorias', to='www.autor')),
            ],
            options={
                'ordering': ['data_entrada'],
            },
        ),
        migrations.AddConstraint(
            model_name='proposicao',
            constraint=models.UniqueConstraint(fields=('tipo', 'numero'), name='unique_numero_por_tipo'),
        ),
    ]
