# Generated by Django 6.0 on 2025-12-27 03:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='texto_parecer',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Texto do Parecer'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='texto_parecer_vencido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Texto do Parecer Vencido'),
        ),
    ]
