# Generated by Django 6.0 on 2025-12-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramitacao',
            old_name='projeto',
            new_name='proposicao',
        ),
    ]
