# Generated by Django 6.0 on 2026-07-10 01:33

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='data_apresentacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='parecer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='relator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_como_relator', to='www.autor'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='reuniao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes', to='www.reuniao'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='texto',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.CreateModel(
            name='ParecerVencido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.CharField(max_length=200)),
                ('texto', django_ckeditor_5.fields.CKEditor5Field()),
                ('data_apresentacao', models.DateField()),
                ('relator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.autor')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.reuniao')),
                ('tramitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres_vencidos', to='www.tramitacao')),
            ],
            options={
                'verbose_name': 'Parecer Vencido',
                'verbose_name_plural': 'Pareceres Vencidos',
                'ordering': ['data_apresentacao'],
            },
        ),
        migrations.DeleteModel(
            name='Parecer',
        ),
    ]
