# Generated by Django 6.0 on 2025-12-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='data_reuniao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
