# Generated by Django 6.0 on 2026-07-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_tramitacao_data_apresentacao_tramitacao_parecer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramitacao',
            name='data_apresentacao',
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='pedido_vista',
            field=models.BooleanField(default=False, verbose_name='Pedido de Vista'),
        ),
    ]
