# Generated by Django 6.0 on 2025-12-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_alter_tramitacao_texto_parecer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='parecer_vencido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
