# Generated by Django 6.0 on 2025-12-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_alter_tramitacao_parecer_vencido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramitacao',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='observacao',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
