# Generated by Django 6.0 on 2026-07-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_remove_tramitacao_data_apresentacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='data_ata_do',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Ata'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='data_edital_do',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Edital'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tem_ata_assinada',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ata Assinada'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tem_conclusao',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tem Conclusão'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tem_conclusao_assinada',
            field=models.BooleanField(blank=True, null=True, verbose_name='Conclusão Assinada'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tem_deliberacao',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tem Deliberação'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tem_deliberacao_assinada',
            field=models.BooleanField(blank=True, null=True, verbose_name='Deliberação Assinada'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tem_edital_assinado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Edital Assinado'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tem_parecer_assinado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Parecer Assinado'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tem_presenca_assinada',
            field=models.BooleanField(blank=True, null=True, verbose_name='Presença Assinada'),
        ),
    ]
