# Generated by Django 6.0 on 2026-07-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_reuniao_data_ata_do_reuniao_data_edital_do_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reuniao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Ordem'),
        ),
        migrations.RemoveField(
            model_name='reuniao',
            name='ano',
        ),
    ]
