# Generated by Django 6.0 on 2026-07-15 10:43

from django.db import migrations, models


def acentuar_tipos(apps, schema_editor):
    Reuniao = apps.get_model("www", "Reuniao")
    Reuniao.objects.filter(tipo="ORDINARIA").update(tipo="ORDINÁRIA")
    Reuniao.objects.filter(tipo="EXTRAORDINARIA").update(tipo="EXTRAORDINÁRIA")


def desacentuar_tipos(apps, schema_editor):
    Reuniao = apps.get_model("www", "Reuniao")
    Reuniao.objects.filter(tipo="ORDINÁRIA").update(tipo="ORDINARIA")
    Reuniao.objects.filter(tipo="EXTRAORDINÁRIA").update(tipo="EXTRAORDINARIA")


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_alter_reuniao_unique_together_alter_reuniao_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='tipo',
            field=models.CharField(choices=[('ORDINÁRIA', 'Ordinária'), ('EXTRAORDINÁRIA', 'Extraordinária')], max_length=20),
        ),
        migrations.RunPython(acentuar_tipos, desacentuar_tipos),
    ]
