# Generated by Django 6.0 on 2026-07-20 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_alter_reuniao_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='alterada_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_alteradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Última Alteração'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='usuario_inclusao',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_incluidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Inclusão'),
        ),
    ]
